version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/service"
    schedule:
      interval: "daily"
    assignees:
      - "sleberknight"
      - "chrisrohr"
    reviewers:
      - "sleberknight"
      - "chrisrohr"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "daily"
    assignees:
      - "sleberknight"
      - "chrisrohr"
    reviewers:
      - "sleberknight"
      - "chrisrohr"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "sleberknight"
      - "chrisrohr"
    reviewers:
      - "sleberknight"
      - "chrisrohr"
      
